# Generated by Django 3.1 on 2020-08-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=30)),
                ('alternative_name', models.CharField(max_length=30)),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datapoll.macaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=4, unique=True)),
                ('ip_address_24', models.CharField(max_length=15)),
                ('ip_address_50', models.CharField(max_length=15)),
                ('mac_24', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_24_ghz', to='datapoll.macaddress')),
                ('mac_50', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_50_ghz', to='datapoll.macaddress')),
            ],
        ),
        migrations.CreateModel(
            name='PacketReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_datetime', models.DateTimeField(auto_now_add=True)),
                ('rss', models.SmallIntegerField()),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datapoll.macaddress')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datapoll.router')),
            ],
        ),
    ]
