# Generated by Django 3.1 on 2020-08-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketReceipt',
            fields=[
                ('packet_datetime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('rss', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('spectrum', models.SmallIntegerField(choices=[(50, '5 GHz'), (24, '2.4 GHz')])),
                ('frequency', models.SmallIntegerField()),
                ('monitor', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('mac_address_hash', models.CharField(max_length=64, unique=True)),
                ('do_not_log', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('hostname', models.CharField(blank=True, max_length=30, null=True)),
                ('alternative_name', models.CharField(max_length=30)),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datapoll.macaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=4, unique=True)),
                ('ip_address_24', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_address_50', models.CharField(blank=True, max_length=15, null=True)),
                ('mac_24', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_24_ghz', to='datapoll.macaddress')),
                ('mac_50', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_50_ghz', to='datapoll.macaddress')),
            ],
        ),
    ]
