# Generated by Django 3.1 on 2020-08-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelessdevice',
            name='hostname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wirelessdevice',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
