# Generated by Django 3.1 on 2020-08-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address_24', models.CharField(max_length=15)),
                ('ip_address_50', models.CharField(max_length=15)),
                ('mac_24', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_24_ghz', to='datapoll.macaddress')),
                ('mac_50', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_50_ghz', to='datapoll.macaddress')),
            ],
        ),
    ]
