# Generated by Django 3.1 on 2020-08-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0002_auto_20200821_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip_address_24',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address_50',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_24_ghz', to='datapoll.macaddress'),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_50',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_for_50_ghz', to='datapoll.macaddress'),
        ),
    ]
