# Generated by Django 3.1 on 2020-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0004_macaddress_do_not_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('spectrum', models.SmallIntegerField(choices=[(50, '5 GHz'), (24, '2.4 GHz')])),
                ('frequency', models.SmallIntegerField()),
                ('monitor', models.BooleanField(default=False)),
            ],
        ),
    ]
