# Generated by Django 3.1 on 2020-08-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0005_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packetreceipt',
            old_name='packet_datetime',
            new_name='receipt_datetime',
        ),
    ]
