# Generated by Django 3.1 on 2020-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0006_auto_20200825_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetreceipt',
            name='id',
        ),
        migrations.AlterField(
            model_name='packetreceipt',
            name='receipt_datetime',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
