# Generated by Django 3.1 on 2020-08-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0007_auto_20200825_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packetreceipt',
            options={'managed': False},
        ),
    ]
