# Generated by Django 3.1 on 2020-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0008_auto_20200825_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='mac_address_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='macaddress',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
