# Generated by Django 3.1 on 2020-08-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoll', '0009_auto_20200825_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='mac_address_hash',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
